### ISSUE TITLE
We do not know who is the fourth member of the team.

### ISSUE THREAD

**Issue by mihalykorodi** [Teaching-projects/SZE-MoSzE-2019-DarkMoor#4]
I would kindly ask you to help us solve this issue @hegyhati @reichelatti .

**Comment by reichelatti** [comment]
Sorry I did not contact you earlier. I joined the class a little late and did not have a team.  One of the members did not join yet so @hegyhati sent me an invitation.

**Comment by reichelatti** [comment]
I hope you do not mind .

**Comment by hegyhati** [comment]
Na sracok, ehhez nem kellett volna issue-t nyitni, de @mihalykorodi  Neked mutattam is, hogy a TEam-ben siman lehetett volna egy beszelgetest elinditani. De vegulis igy is megoldodott a dolog.

**Comment by mihalykorodi** [comment]
@reichelatti I sent you a contact in the team discussion.
